import type { UserSummary } from './user';

/**
 * The completion state of a milestone.
 * - "upcoming"  — deadline is in the future; tasks are in progress.
 * - "at-risk"   — deadline is approaching but not all tasks are done.
 * - "missed"    — deadline has passed with incomplete tasks.
 * - "completed" — all linked tasks are done and the milestone is achieved.
 */
export type MilestoneStatus = 'upcoming' | 'at-risk' | 'missed' | 'completed';

/**
 * A milestone is a significant checkpoint in a project — typically a deadline,
 * release, or deliverable that groups a set of tasks together.
 *
 * On the canvas, milestones appear as a distinct visual layer (e.g. a dashed
 * boundary or a diamond node) that encloses or references their member tasks.
 */
export interface Milestone {
  /**
   * Unique identifier — UUID generated by the database.
   */
  id: string;

  /**
   * The project this milestone belongs to.
   * Foreign key to Project.id.
   */
  projectId: string;

  /**
   * Short name of the milestone shown on the canvas and in the timeline view.
   * e.g. "v1.0 Launch", "Design Handoff", "Q3 Review"
   * Max 80 characters.
   */
  name: string;

  /**
   * Optional longer description explaining what "done" looks like for this milestone.
   * Supports markdown.
   */
  description?: string;

  /**
   * The hard deadline for this milestone.
   * ISO 8601 date string (YYYY-MM-DD).
   * All linked tasks should ideally be complete by this date.
   */
  dueDate: string;

  /**
   * Derived completion state of the milestone.
   * Computed from: task statuses, current date vs. dueDate.
   */
  status: MilestoneStatus;

  /**
   * Percentage of linked tasks that are in "done" or "cancelled" status.
   * Range: 0–100. Computed on the server; stored for fast progress bar rendering.
   */
  completionPercent: number;

  /**
   * IDs of all tasks that contribute to this milestone.
   * A task can belong to at most one milestone.
   * Stored as an array of Task.id values.
   */
  taskIds: string[];

  /**
   * Accent color for this milestone used on the canvas boundary and timeline.
   * Stored as a hex string (e.g. "#06b6d4").
   * Defaults to the parent project's color if not explicitly set.
   */
  color: string;

  /**
   * The user who created the milestone.
   */
  createdBy: UserSummary;

  /** ISO 8601 timestamp of milestone creation. */
  createdAt: string;

  /** ISO 8601 timestamp of the most recent edit. */
  updatedAt: string;

  /**
   * ISO 8601 timestamp of when the milestone was marked "completed".
   * Null if still active.
   */
  completedAt?: string;
}
