import type { UserSummary } from './user';

/**
 * The overall health state of a project, derived from its task statuses.
 * - "on-track"   — no blocked tasks, all milestones within deadline.
 * - "at-risk"    — one or more tasks are blocked or overdue but not critical.
 * - "off-track"  — critical path is delayed or a milestone has been missed.
 * - "completed"  — all tasks are done.
 * - "archived"   — project is read-only; no further edits permitted.
 */
export type ProjectStatus = 'on-track' | 'at-risk' | 'off-track' | 'completed' | 'archived';

/**
 * Controls who can do what inside a project.
 * - "owner"       — full control: edit, delete, manage members.
 * - "editor"      — can create/edit/delete tasks and dependencies.
 * - "commenter"   — can view and comment; cannot change tasks.
 * - "viewer"      — read-only access.
 */
export type ProjectRole = 'owner' | 'editor' | 'commenter' | 'viewer';

/**
 * Links a user to a project with a specific permission level.
 */
export interface ProjectMember {
  /** The user being granted access. */
  user: UserSummary;

  /** The permission level this user has within the project. */
  role: ProjectRole;

  /** ISO 8601 timestamp of when this user was added to the project. */
  addedAt: string;
}

/**
 * Represents a single project — the top-level container for a task graph.
 */
export interface Project {
  /**
   * Unique identifier — UUID generated by the database.
   */
  id: string;

  /**
   * Human-readable project name shown in the sidebar and page titles.
   * Max 100 characters.
   */
  name: string;

  /**
   * Optional longer description explaining the project's goal or scope.
   * Supports plain text; rendered in the project settings panel.
   */
  description?: string;

  /**
   * Derived health status of the project. Computed server-side from
   * task statuses and milestone deadlines; stored for fast querying.
   */
  status: ProjectStatus;

  /**
   * Accent color for this project used in the sidebar and node borders.
   * Stored as a hex string (e.g. "#7c3aed").
   */
  color: string;

  /**
   * Optional URL to a project cover image displayed on the dashboard card.
   */
  coverImageUrl?: string;

  /**
   * All users who have access to this project, including their roles.
   */
  members: ProjectMember[];

  /**
   * The user who created and owns the project.
   * Always has the "owner" ProjectRole.
   */
  ownedBy: UserSummary;

  /**
   * Optional target completion date for the entire project.
   * ISO 8601 date string (YYYY-MM-DD).
   */
  dueDate?: string;

  /**
   * Tags for filtering and grouping projects on the dashboard.
   * e.g. ["q3-2025", "mobile", "infra"]
   */
  tags: string[];

  /**
   * ISO 8601 timestamp of project creation.
   */
  createdAt: string;

  /**
   * ISO 8601 timestamp of the last change to the project record itself
   * (name, description, settings). Does not update on task edits.
   */
  updatedAt: string;

  /**
   * ISO 8601 timestamp set when the project is archived.
   * Null if the project is active.
   */
  archivedAt?: string;
}
