import type { UserSummary } from './user';

/**
 * Lifecycle state of a task.
 * - "todo"        — not yet started.
 * - "in-progress" — actively being worked on.
 * - "in-review"   — work done; awaiting approval or QA.
 * - "blocked"     — cannot proceed because an upstream dependency is incomplete.
 * - "done"        — finished and accepted.
 * - "cancelled"   — will not be completed; kept for historical context.
 */
export type TaskStatus =
  | 'todo'
  | 'in-progress'
  | 'in-review'
  | 'blocked'
  | 'done'
  | 'cancelled';

/**
 * Urgency level of a task.
 * Used to color-code node borders and sort tasks in list views.
 */
export type TaskPriority = 'low' | 'medium' | 'high' | 'critical';

/**
 * The (x, y) position of a node on the infinite canvas.
 * Persisted so each user's layout is preserved between sessions.
 */
export interface NodePosition {
  /** Horizontal offset from the canvas origin in pixels. */
  x: number;
  /** Vertical offset from the canvas origin in pixels. */
  y: number;
}

/**
 * A single comment left on a task by a collaborator.
 */
export interface TaskComment {
  /** Unique identifier for the comment. */
  id: string;

  /** The user who wrote the comment. */
  author: UserSummary;

  /** Plain-text or markdown comment body. */
  body: string;

  /** ISO 8601 timestamp of when the comment was posted. */
  createdAt: string;

  /**
   * ISO 8601 timestamp of the last edit.
   * Undefined if the comment has never been edited.
   */
  editedAt?: string;
}

/**
 * A single entry in the task's audit trail.
 */
export interface ActivityEntry {
  /** Unique identifier for this log entry. */
  id: string;

  /** The user who triggered the change. */
  actor: UserSummary;

  /**
   * Machine-readable action type.
   * e.g. "status_changed", "assignee_changed", "comment_added"
   */
  action: string;

  /**
   * Human-readable description of what changed.
   * e.g. "Changed status from todo → in-progress"
   */
  description: string;

  /** ISO 8601 timestamp of the action. */
  occurredAt: string;
}

/**
 * Represents a single task — the primary node type on the project graph.
 */
export interface Task {
  /**
   * Unique identifier — UUID generated by the database.
   */
  id: string;

  /**
   * The project this task belongs to.
   * Foreign key to Project.id.
   */
  projectId: string;

  /**
   * Optional milestone this task contributes to.
   * Foreign key to Milestone.id. Null if not assigned to a milestone.
   */
  milestoneId?: string;

  /**
   * Short, descriptive title of the task shown on the canvas node.
   * Max 120 characters.
   */
  title: string;

  /**
   * Longer description with context, acceptance criteria, or notes.
   * Supports markdown. Shown in the task detail side panel.
   */
  description?: string;

  /**
   * Current lifecycle state of the task.
   * The "blocked" status is set automatically when any upstream dependency
   * remains incomplete; it can also be set manually.
   */
  status: TaskStatus;

  /**
   * Urgency of this task relative to others in the project.
   * Renders as a colored badge on the canvas node.
   */
  priority: TaskPriority;

  /**
   * The user responsible for completing this task.
   * Undefined if unassigned.
   */
  assignee?: UserSummary;

  /**
   * Target completion date for the task.
   * ISO 8601 date string (YYYY-MM-DD).
   */
  dueDate?: string;

  /**
   * Estimated effort in hours. Used for workload balancing and analytics.
   */
  estimatedHours?: number;

  /**
   * Actual hours logged against this task.
   * Updated by assignees or integrations (e.g. Toggl, Harvest).
   */
  loggedHours?: number;

  /**
   * The position of this task's node on the canvas.
   * Persisted per-project so layouts survive page reloads.
   */
  position: NodePosition;

  /**
   * Labels / tags for filtering and grouping tasks.
   * e.g. ["frontend", "auth", "bug"]
   */
  labels: string[];

  /**
   * All comments on this task, ordered oldest → newest.
   */
  comments: TaskComment[];

  /**
   * Chronological log of all changes made to this task.
   */
  activityLog: ActivityEntry[];

  /**
   * The user who created the task.
   */
  createdBy: UserSummary;

  /** ISO 8601 timestamp of task creation. */
  createdAt: string;

  /** ISO 8601 timestamp of the most recent edit to any task field. */
  updatedAt: string;

  /**
   * ISO 8601 timestamp of when the task was marked "done" or "cancelled".
   * Null if still active.
   */
  completedAt?: string;
}
