/**
 * Represents a registered user of the platform.
 */
export interface User {
  /**
   * Unique identifier for the user — UUID generated by Supabase Auth.
   */
  id: string;

  /**
   * The user's display name shown on node assignee badges and comments.
   */
  name: string;

  /**
   * Email address. Used for authentication and notification delivery.
   * Must be unique across all users.
   */
  email: string;

  /**
   * Optional URL to the user's profile picture.
   * Falls back to an auto-generated avatar (initials + color) when absent.
   */
  avatarUrl?: string;

  /**
   * The user's role within the platform at the global level.
   * - "admin"  — can manage all projects and users in the workspace.
   * - "member" — standard access; project-level permissions apply.
   * - "guest"  — read-only access unless explicitly granted more by a project owner.
   */
  role: 'admin' | 'member' | 'guest';

  /**
   * ISO 8601 timestamp of when the user account was created.
   */
  createdAt: string;

  /**
   * ISO 8601 timestamp of the user's most recent activity.
   * Useful for surfacing active collaborators.
   */
  lastActiveAt: string;
}

/**
 * A lightweight version of User used when embedding user info inside
 * tasks, comments, or activity logs — avoids re-fetching the full record.
 */
export interface UserSummary {
  id: string;
  name: string;
  avatarUrl?: string;
}
